spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/${LOCAL_MYSQL_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=DISABLED&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&logger=Slf4JLogger
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 35
      minimum-idle: 35
      connection-timeout: 30000
      max-lifetime: 297000
      keepalive-time: 200000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        socketTimeout: 5000
        connectTimeout: 5000
        profileSQL: true
        logSlowQueries: true
        slowQueryThresholdMillis: 2000
        explainSlowQueries: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password:
server:
  tomcat:
    max-connections: 5000
    accept-count: 200
    threads:
      max: 30
      min-spare: 10
    connection-timeout: 20000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:3306/${DEV_MYSQL_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=DISABLED&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&logger=Slf4JLogger
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 35
      minimum-idle: 35
      connection-timeout: 30000
      max-lifetime: 297000
      keepalive-time: 200000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        socketTimeout: 5000
        connectTimeout: 5000
        profileSQL: true
        logSlowQueries: true
        slowQueryThresholdMillis: 2000
        explainSlowQueries: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  tomcat:
    max-connections: 5000
    accept-count: 200
    threads:
      max: 30
      min-spare: 10
    connection-timeout: 20000
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.zaxxer.hikari.pool.HikariPool: debug
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_HOST}:3306/${PROD_MYSQL_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=DISABLED&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&logger=Slf4JLogger
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 35
      minimum-idle: 35
      connection-timeout: 30000
      max-lifetime: 297000
      keepalive-time: 200000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        socketTimeout: 5000
        connectTimeout: 5000
        profileSQL: true
        logSlowQueries: true
        slowQueryThresholdMillis: 2000
        explainSlowQueries: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false
  flyway:
    enabled: false
server:
  tomcat:
    max-connections: 5000
    accept-count: 200
    threads:
      max: 30
      min-spare: 10
    connection-timeout: 20000
logging:
  level:
    org.hibernate.SQL: error
